#!/bin/bash

echo "DataSink Demo"
echo "============="
echo ""
echo "This script demonstrates how to run the DataSink server and client."
echo ""
echo "To run the server (in one terminal):"
echo "  cargo run"
echo ""
echo "To run the example client (in another terminal):"
echo "  cargo run --example client"
echo ""
echo "To run with custom settings:"
echo "  DATABASE_URL=sqlite://mydb.db SERVER_ADDRESS=0.0.0.0:8080 cargo run"
echo ""
echo "To run tests:"
echo "  cargo test"
echo ""
echo "To check code quality:"
echo "  cargo fmt && cargo clippy"